build-script-7.7.3.sh
Rename build script file for 7.7.3.
Update version to 7.7.3 and dependencies.
=> Update to build 7.7.3

README.md, build-script-7.7.5.sh
Rename script file for version 7.7.5.
Update build script and readme for 7.7.5.
=> 7.7.5 update

build-script-7.7.5.sh
Retrieve the versions directly by reading the Bonita Studio pom instead
of declaring them manually. So the maintenance cost is reduced and less
has to be changed when uprading the Bonita version.
This applies to
- studio watchdog
- theme builder
- uid
=> feat(dependencies): detect them from studio pom

build-script.sh
even if this has no effect on script, it may be removed
=> remove duplicated line

build-script.sh
Avoid issue like the one described in https://community.bonitasoft.com/questions-and-answers/gradle-build-fail-errors-when-building-bonita
=> prerequisites: check java version

.travis.yml, .travis/maven/toolchains.xml, README.md, build-script.sh
This ensures that the solution works on a fresh environment.
=> Introduce Travis CI Linux build

README.md, build-script.sh
=> feat(7.10): support 7.10.0.beta build

README.md, build-script.sh
Merge master into dev and update files for 7.10
=> [dev] merge master into dev

build-script.sh
I suggest that we merge this one on the dev branch and then merge dev into master
That way will be ready for the 7.10.0 GA
=> [dev] Build Bonita 7.10.0

.github/workflows/ci.yml, README.md
For users
- Bonita version support
- branch or tags to use
For contributors
- new developing dedicated section
- add new Bonita version support
- create tag and release
=> README improvements mainly for contributors

build-script.sh
=> fix(build script): fix bash shebang

build-script.sh
Update Bonita version to 7.11.2
=> Update for 7.11.2

build-script.sh
Update release Bonita version with 7.10.6
=> Update for version 7.10.6

.github/workflows/ci.yml, build-script.sh
=> [dev] start building Bonita 7.12

build-script.sh
Update Bonita version to 7.11.3
=> [real]Update build-script.sh

.github/workflows/ci.yml, .travis.yml, README.md
Travis CI: 16.04 to 18.04
GitHub Actions: use specific runner versions instead of 'latest'
=> CI Build: ubuntu environment upgrade

build-script.sh
=> tr(version): update to latest weekly

.github/workflows/ci.yml, README.md, build-script.sh
Fixes https://github.com/Bonitasoft-Community/Build-Bonita/issues/80
=> tr(ubuntu): add ubuntu build

.github/workflows/ci.yml
=> chore: Adding slack notification when build failed

.github/workflows/ci.yml, .gitignore, README.md, build-script.sh
What has been done:
> :bookmark: **TODO** Remove the `dev` branch and rename `master` into `main`. As community doesn't have maintenance version aymore, there is no need for `dev`+ `master` branch.
Fixes https://github.com/Bonitasoft-Community/Build-Bonita/issues/41
=> feat(build): support branches build

README.md
* Add Github action section
* Add  Github artifacts retention limit
* Remove maintenance version references
Fixes https://github.com/Bonitasoft-Community/Build-Bonita/issues/52
=> doc(README): add github action

.github/workflows/ci.yml
Use latest macos env.
Current one is deprecated.
=> fix(macos): Update env to macos-12
